DEVELOPER.md
Commands are formatted as code.
Also splits nicely separate commands into different lines (as currently multiple commands are packed into one line).
=> Formatting changes

core/src/main/scala/core/ServiceDescriptionValidator.scala, core/src/test/scala/core/ServiceMethodsSpec.scala
=> Validate that all operations have a method defined

lib/src/main/scala/VersionTag.scala, lib/src/test/scala/VersionTagSpec.scala, schema/scripts/20150301-112236.sql
=> 271 release tags should sort first

TODO, api/app/actors/EmailActor.scala, api/app/actors/MainActor.scala, api/app/db/VersionsDao.scala, api/app/lib/ServiceDiff.scala, api/app/views/emails/versionCreated.scala.html, api/test/lib/OriginalUtilSpec.scala, api/test/lib/ServiceDiffSpec.scala, api/test/lib/TestHelper.scala, lib/src/main/scala/Text.scala
- Email notifications when a version is updated now includes the diff
- Broken into breaking and non breaking changes
=> Implement function to diff two versions of a service

swagger/src/main/scala/me/apidoc/swagger/Parser.scala, swagger/src/main/scala/me/apidoc/swagger/translators/Resolver.scala, swagger/src/test/resources/petstore-with-external-docs-and-complex-path.json, swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala
- Fixes 356
- SwaggerServiceValidatorSpec test passes.
=> 356 use model from schema

.gitignore
=> add .idea and .idea_modules dirs to .gitignore

swagger/src/main/scala/me/apidoc/swagger/translators/Field.scala, swagger/src/test/resources/refs.json, swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala
- Merged latest commits from Master into branch
- Added additional test for the Swagger json w refs for properties- passes
- Everything looks good with your code!
=> 353 swagger refs

api/app/controllers/Applications.scala
- Eventually will replace with fine grained permissions but
for the moment we need to allow org members to update their
applications (current use case is to publish API following
the open source release of a project)
- Fixes #367
=> Allow any org member to update an application

www/app/controllers/ApplicationSettings.scala
- small improvement to catch an error on mistyped URLs,
redirecting user appropriately (vs http 500)
=> Add redirect w/ message in app settings if app key not found

core/src/main/scala/core/TypeValidator.scala, core/src/main/scala/core/builder/ServiceSpecValidator.scala, core/src/main/scala/core/builder/api_json/ServiceBuilder.scala, core/src/main/scala/core/builder/api_json/Types.scala, core/src/test/scala/core/ImportServiceSpec.scala, core/src/test/scala/core/TypeValidatorSpec.scala, core/src/test/scala/core/UnionTypeSpec.scala
- this was a bit of a nasty bug as it meant we had to finish up
work related to type inferrence across models / unions / primitives
- see test cases for specifics on how to replicate
=> Resolve inferred types for imported services

core/src/main/scala/core/builder/ServiceSpecValidator.scala, core/src/test/scala/core/ServicePathParametersSpec.scala, spec/apidoc-api.json, spec/apidoc-generator.json
=> Validate path parameters

api/app/db/UserPasswordsDao.scala
- Currently on macbook leads to avg time of 866 ms
=> Adjust bcrypt rounds to 13

www/app/views/doc/apiJson.scala.html
=> Add api.json docs for recently added 'attributes'

core/src/main/scala/core/builder/api_json/ApiJsonServiceValidator.scala, core/src/main/scala/core/builder/api_json/ServiceBuilder.scala
=> Display validation errors on attributes

api/app/actors/Emails.scala, api/app/actors/TaskActor.scala
=> Fix filter on versions.create email to limit to watched apps

spec/apidoc-swagger.json
@mbryzek If you're good with the remaining TODOs (in description fields, since this is JSON), feel free to merge.
=> Start documentation of swagger spec

api/app/lib/ExampleJson.scala
* Distinguish between union types with and without discriminator field
* Wrap primitives in a "value" field.
=> Correctly generate example json for union types

api/app/lib/ExampleJson.scala, api/test/lib/ExampleJsonSpec.scala, www/app/views/versions/exampleJson.scala.html, www/app/views/versions/show.scala.html
=> Lookup parent union type when serializing models, enums

api/app/Filters.scala, build.sbt
This enables the new ui to have access to the backend
=> Add cors support to api

www/app/controllers/DocController.scala, www/app/lib/Util.scala, www/app/views/doc/apiTokens.scala.html, www/app/views/doc/main.scala.html, www/app/views/tokens/index.scala.html, www/conf/routes
- Fixes https://github.com/mbryzek/apidoc/issues/526
=> Add docs on using apidoc tokens

api/app/controllers/Versions.scala
When generating example json for a model type that contains enums,
unions or models from imports, we need to look these up correctly and
include them in the parent service, with the correct namespace prefix.
=> Fix example json for services with imports

swagger/src/main/scala/me/apidoc/swagger/Parser.scala, swagger/src/main/scala/me/apidoc/swagger/SwaggerData.scala, swagger/src/main/scala/me/apidoc/swagger/translators/Operation.scala, swagger/src/test/resources/petstore-enums.json, swagger/src/test/resources/petstore-external-docs-example-security.json, swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala
Swagger data covered:
* schemes (service and operation level)
* host, basePath (service level)
* tags, operationId, summary (operation level)
=> More Swagger data imported as Apidoc attributes.

www/app/views/doc/apiJson.scala.html
- See https://github.com/mbryzek/apidoc/issues/626%23issuecomment-307346393
=> Clarify docs on default values

SWAGGER.md, swagger/src/main/scala/me/apidoc/swagger/Parser.scala
=> Add explanation about array models not being supported

api/app/db/generators/GeneratorsDao.scala, api/test/db/generators/GeneratorsDaoSpec.scala, api/test/db/generators/Util.scala
=> Fix bug with generator attribute serialization

api/app/db/EmailVerificationsDao.scala, api/app/db/OrganizationDomainsDao.scala, api/app/db/OrganizationsDao.scala, api/app/db/UsersDao.scala, api/test/db/OrganizationDomainDaoSpec.scala
- Fixes https://github.com/apicollective/apibuilder/issues/694
=> Allow multiple domains to share an org

api/app/controllers/Versions.scala, api/app/lib/ExampleJson.scala, api/conf/routes, api/test/lib/ExampleJsonSpec.scala, app/app/controllers/Versions.scala, app/app/views/versions/show.scala.html, app/app/views/versions/unionTypes.scala.html, app/conf/routes, generated/app/ApicollectiveApibuilderApiV0Client.scala, spec/apibuilder-api.json
=> Generate examples for all union types, instead of just the first in a union

spec/apibuilder-api.json, spec/apibuilder-internal.json, spec/apibuilder-spec.json
Some of the specs had been committed to source with a mix of tabs and spaces for indentation. It looked mostly okay with tab stops set to 8, but with my tab stops set to 2 the alignment was pretty bad.
All tabs have been removed from these files.
=> Normalize spec whitespace.

generated/app/ApicollectiveApibuilderApiV0Client.scala, generated/app/ApicollectiveApibuilderCommonV0Models.scala, generated/app/ApicollectiveApibuilderGeneratorV0Client.scala, generated/app/ApicollectiveApibuilderInternalV0Models.scala, generated/app/ApicollectiveApibuilderSpecV0Client.scala
via the CLI:  apibuilder update
=> regenerate models and clients

api/app/db/VersionsDao.scala, api/test/db/VersionsDaoSpec.scala
In short, ~ will allow you to specify the minimum version, and lets the last digit go up as per sem ver convention.
e.g. ~1.0 => highest version >= 1.0.0 < 2.0.0
e.g. ~1.2=> highest version >=1.2.0 < 2.0.0
e.g. ~1.2.3=> highest version >=1.2.3 < 1.3.0
new usage e.g. 
http://localhost:9000/hbcmobilex/mobile-middleware-api/~1.0
http://localhost:9000/hbcmobilex/mobile-middleware-api/latest
http://localhost:9000/hbcmobilex/mobile-middleware-api/1.2.3
should both work as before
=> Added capability to specify api version using ~operator.

spec/apibuilder-postman-collection-v2-1.json
Specification of Postman Collection Format v2.1 using the ApiBuilder schema. 
Further information about Postman Collection Format v2.1 can be found at https://schema.getpostman.com/json/collection/v2.1.0/docs/index.html
You can also take a look at the PR with Postman Collection Generator in apibuilder-generator repo
https://github.com/apicollective/apibuilder-generator/pulls
(which bases on schema from this PR)
Sample specification upload available at:
https://app.apibuilder.io/apicollective/apibuilder-postman-collection-v2-1/latest
=> Postman Collection Format v2.1 definition

api/app/util/UserAgent.scala
The user agent is copied into the header of every file. It would be nice to be able to cmd+click on that link. This PR makes that possible.
=> add https:// to user agent

swagger/src/main/scala/me/apidoc/swagger/SchemaType.scala, swagger/src/test/resources/petstore-enums.json, swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala
Mapped into ApiBuilder object type.
=> Fix import Swagger object type. Fixes #801

api/app/controllers/Code.scala, api/app/controllers/Versions.scala, api/app/util/ApiBuilderServiceImportResolver.scala, api/app/util/ApibuilderServiceImportResolver.scala, api/test/db/Helpers.scala, api/test/db/VersionsDaoSpec.scala, api/test/util/ApiBuilderServiceImportResolverSpec.scala, api/test/util/ApibuilderServiceImportResolverSpec.scala, core/src/test/scala/helpers/RandomHelpers.scala, core/src/test/scala/helpers/ServiceHelpers.scala
- fixes https://github.com/apicollective/apibuilder/issues/833
=> Remove duplicate imported services from generator invocation form

api/app/controllers/Code.scala, app/app/lib/ApiClientProvider.scala, app/app/lib/Util.scala, lib/src/main/scala/Hacks.scala
=> [hack] Use k8s services if running on k8s

api/app/controllers/Code.scala, app/app/lib/ApiClientProvider.scala, app/app/lib/Util.scala, lib/src/main/scala/Hacks.scala
This reverts commit bb0b5574f7541ee2a8c05b2ec20b265276689c71.
=> Revert "[hack] Use k8s services if running on k8s (#845)"

api/app/controllers/Code.scala, api/app/lib/OrgAttributeUtil.scala
- First step to see if we can safely implement this change
=> Code: Log usage of org attributes

build.sbt, deploy/apibuilder-api/templates/deployment.yaml, deploy/apibuilder-app/templates/deployment.yaml
Updated dependency in build.sbt and configured `deployment.yaml`
=> FDTN-210: DD Agent Rollout

.travis.yml, core/src/main/scala/core/builder/ServiceSpecValidator.scala, core/src/test/scala/core/InterfaceSpec.scala, lib/src/main/scala/Kind.scala
This reverts commit cd1dcecb2a6c9879e1d4842c56724a559eb9be35.
=> Validate that field type is not an interface

build.sbt, core/src/main/scala/core/DuplicateJsonParser.scala, core/src/main/scala/core/builder/api_json/ApiJsonServiceValidator.scala, core/src/test/scala/core/DuplicateFieldValidatorSpec.scala, core/src/test/scala/core/TypeValidatorSpec.scala, spec/apibuilder-api.json
- Detect duplicate fields
- wip
- Fix
=> Detect duplicate fields in api json files

api/app/modules/ProductionClientModule.scala, core/src/main/scala/core/builder/api_json/templates/ModelMerge.scala, core/src/test/scala/core/builder/api_json/templates/ModelMergeSpec.scala
This reverts commit bacff8711c09d3bec43bd045eb2aefc58f718995.
=> Template interfaces: Only include fields that are the same (#914)

app/app/lib/Markdown.scala, build.sbt
=> Replace deprecated pegdown markdown parser with flexmark

TODO, api/app/actors/EmailActor.scala, api/app/actors/Emails.scala, api/app/lib/EmailUtil.scala, app/app/controllers/ApiBuilderController.scala, build.sbt, project/build.properties, project/plugins.sbt
- **wip**
- **wip**
- **wip**
- **wip**
- **wip**
=> Upgrade dependencies

api/app/actors/MainActor.scala, api/app/actors/TaskActor.scala, api/app/db/InternalMigrationsDao.scala, api/app/db/TasksDao.scala, api/app/db/VersionsDao.scala, api/app/util/ProcessDeletes.scala, api/test/db/TasksDaoSpec.scala, api/test/util/ProcessDeletesSpec.scala
- **wip**
- **wip**
- **wip**
- **wip**
- **wip**
- **wip**
- **wip**
- **wip**
=> Cascade deletions
