generator/app/models/ning/NingClientGenerator.scala

Ideally this thing would have a singleton thread pool instance for
all client instances in the JVM, but this change is at least an
improvement over what it does now.

ning client should reuse a single thread pool

---

www/public/stylesheets/main.css

The z-index of the navbar was set incorrectly, allowing the content to be positioned over the nav dropdown. This prevented the user Logout button from functioning properly.

Fixed styling on navbar allowing access to Logout button

---

api/app/Global.scala

the existing onBadRequest and onServerError methods
make it impossible to debug basic things like a missing
Content-Type header

don't swallow error messages in the API

---

api/app/actors/MainActor.scala
api/app/controllers/Applications.scala
api/app/controllers/AuthenticatedRequest.scala
api/app/controllers/Code.scala
api/app/controllers/Generators.scala
api/app/controllers/MembershipRequests.scala
api/app/controllers/Memberships.scala
api/app/controllers/Organizations.scala
api/app/controllers/Subscriptions.scala
api/app/controllers/Tokens.scala
api/app/controllers/Validations.scala
api/app/controllers/Versions.scala
api/app/controllers/Watches.scala
api/app/db/Authorization.scala
api/app/db/SubscriptionsDao.scala
api/app/db/VersionsDao.scala
api/app/db/WatchesDao.scala
api/app/lib/DatabaseServiceFetcher.scala
api/app/lib/ServiceUri.scala
api/test/db/VersionsDaoSpec.scala
api/test/lib/ServiceUriSpec.scala
core/src/main/scala/core/ServiceFetcher.scala
core/src/main/scala/core/builder/OriginalValidator.scala
core/src/main/scala/core/builder/api_json/ApiJsonServiceValidator.scala
core/src/main/scala/core/builder/api_json/ServiceBuilder.scala
core/src/test/scala/core/FileServiceFetcher.scala
core/src/test/scala/core/ImportServiceSpec.scala
core/src/test/scala/core/ImporterSpec.scala
generated/app/ApidocApi.scala
www/app/controllers/Generators.scala

- Re-implement how imports work - now fetch imported services directly
from the db by parsing the URL for the service to identify the org/app/version
- Add authorization so that private services that the user has access to can also
be imported. Previously only public services were supported.

Import private services

---

api/app/lib/OriginalUtil.scala
api/test/lib/OriginalUtilSpec.scala
script/upload
www/app/views/doc/apiJson.scala.html

- Fixes #326
- Invalid json was not being checked by original util
which propagated up as a 500
- Catch parse errors here so we can report the error of
invalid JSON to the user

Fix bug that prevented error reporting to user

---

core/src/main/scala/core/builder/api_json/InternalServiceForm.scala
core/src/test/scala/core/ServiceValidatorSpec.scala

- Fixes #333
- Enables user to specify UUID or uuid and both will work consistently
using the primitive's actual name (e.g. uuid) in the service
definition

Fix bug with case sensitive primitive type names

---

DEVELOPER.md

Found that it was not clear at first glance that code generation is a separate concern from apidoc proper.

Add link to apidoc-generator in DEVELOPER.md

---

core/src/test/resources/simple-w-array.json
core/src/test/resources/simple-without-array.json
core/src/test/scala/core/OriginalValidatorSpec.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Field.scala

- Add two tests and two jsons
- One that contains an array of strings in the parameter list and fails to validate
- One that contains a string in stead on an array of strings in the parameter list and successfully validates

361 apidoc can't validate Swagger with arrays in parameter list

---

api/app/actors/EmailActor.scala
api/app/actors/Emails.scala
api/app/actors/TaskActor.scala
api/test/actors/EmailsSpec.scala

- Idea is to filter at email delivery time whether or not the particular
user should receive that message. For example, if a user leaves an org,
we should only send updates for public projects

Email authorization

---

www/app/views/versions/show.scala.html

I've noticed some people don't realize history is recorded.
However, history is an amazing feature!
Make it more prominent on the application version page
I opted to put it close to versioning/watching, as it is closely related
to those functions

Make history link more prominent

---

TODO
api/app/actors/GeneratorServiceActor.scala
api/app/actors/TaskActor.scala
api/app/controllers/GeneratorServices.scala
api/app/db/generators/GeneratorsDao.scala
schema/scripts/20151208-200931.sql

- Fix duplicate key error when syncing generators
- Do not assume that a generator paginates. This implementation
does not depend on a blank generator set - and instead terminates
if page size < limit

Fix error w/ validation of generator keys

---

core/src/main/scala/core/builder/ServiceSpecValidator.scala
core/src/test/scala/core/TestHelper.scala
core/src/test/scala/core/UnionTypeSpec.scala

- this avoids a race condition where, for example:
- service "common" defines a model named reference
- service "user" imports common and defines a union named "user_union" of types "user" and "common.reference"
The problem is that the code generation for common.reference occurs BEFORE user and thus in typed languages where we want to annotate that the Reference class extends UserUnion - we cannot as at the time of code generation for the Reference class we do not know that the union type "user_union" exists.

Validate types in a union are not imported

---

core/src/main/scala/core/builder/api_json/InternalServiceForm.scala
core/src/test/scala/core/ServiceValidatorSpec.scala

Apidoc models (i.e. Operation - https://github.com/mbryzek/apidoc/blob/master/generated%2Fapp%2FBryzekApidocSpecV0Client.scala#L145) allow for an optional "attributes" field, but uploading a spec with this field results in the following error:
```sh
- Resource[view] GET /<sample_path> Unrecognized element[attributes]
```
A few models are currently validating "attributes" (i.e. https://github.com/mbryzek/apidoc/blob/master/core%2Fsrc%2Fmain%2Fscala%2Fcore%2Fbuilder%2Fapi_json%2FInternalServiceForm.scala#L451)
Similar validation has been added to the remaining models that include an optional "attributes" field.

validate optional attributes

---

swagger/src/main/scala/me/apidoc/swagger/SchemaType.scala
swagger/src/main/scala/me/apidoc/swagger/translators/SchemaType.scala
swagger/src/test/resources/petstore-with-external-docs.json
swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala

Swagger doesn't support these, but Apidoc does - no reason to block them.

Support additional formats in Swagger import

---

swagger/src/main/scala/me/apidoc/swagger/Util.scala
swagger/src/test/resources/petstore-with-external-docs-and-complex-path.json
swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala

In the test example,
```
/store/{store_id}/pets/{product_code}
```
was showing up in apidoc as
```
/store/:store_id}/pets/{product_code
```
but should have been
```
/store/:store_id/pets/:product_code
```

Fix bug with multiple paramters in the path

---

api/app/lib/Email.scala
build.sbt

SendGrid 3.0.0 Upgrade
V3 API Reference: 
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html
V3 Java Client and API Usage Example:
https://github.com/sendgrid/sendgrid-java#quick-start

upgrade com.sendgrid.sendgrid-java 2.2.2=>3.0.0

---

core/src/main/scala/core/builder/ServiceSpecValidator.scala
project/plugins.sbt

- No reason why a user cannot choose to provide two sections for each resource
- Ultimately paths are important which are already enforced

Remove check for duplicate resources

---

api/app/db/VersionsDao.scala

- avoids need to resolve dependencies in order
- fixes bug where we do not upgrade all services to latest spec

Recursively migrate services to latest service spec

---

lib/src/main/scala/UrlKey.scala

For example see http://www.apidoc.me/bryzek/apidoc-api/latest
com.bryzek.apidoc.generator.v0.models.healthcheck resource
the GET operations can't be expanded

Remove period (".") characters from url keys, as they break onclick events

---

www/app/lib/TypeLabel.scala

Instead of the version of the imported model, the type is displayed with
the version of the importing model.

Imported model types are displayed with wrong version

---

www/app/views/versions/imports.scala.html

Instead of linking to e.g
`http://www.apidoc.me/bryzek/apidoc-common/latest/service.json`, the
documentation should link to the documentation of the linked model, ie.
to `http://www.apidoc.me/bryzek/apidoc-common/latest`

Import in documentation should link to documentation instead of service.json

---

core/src/main/scala/core/builder/ServiceSpecValidator.scala
core/src/test/scala/core/ServiceValidatorSpec.scala

- too strict for models - and only care about plurals when exposing as resources

Relax plural check to resources only

---

swagger/src/main/scala/me/apidoc/swagger/Parser.scala
swagger/src/main/scala/me/apidoc/swagger/Util.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Operation.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Parameter.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Resource.scala
swagger/src/test/resources/petstore-enums.json
swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala

* operations with no 200 response: can't determine the resource name to properly build a name for the enum type;
* trying to find the model name by URL (see [here](https://github.com/mbryzek/apidoc/blob/master/swagger/src/main/scala/me/apidoc/swagger/translators/Parameter.scala#L53)) seems not robust enough;
* camel case not kept in the generated enum type name when the model name is composed by multiple words: e.g. ReservationResponse --> ReservationresponseBannerPostPath

Fixes #607. ServiceSpecValidator errors on some param enum edge cases.

---

api/test/lib/OriginalUtilSpec.scala
swagger/src/main/scala/me/apidoc/swagger/Parser.scala
swagger/src/main/scala/me/apidoc/swagger/SwaggerData.scala
swagger/src/main/scala/me/apidoc/swagger/Util.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Model.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Operation.scala
swagger/src/test/resources/petstore-external-docs-example-security.json
swagger/src/test/scala/me/apidoc/swagger/SwaggerDataSpec.scala
swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala
swagger/src/test/scala/me/apidoc/swagger/UtilSpec.scala

Swagger data covered in this PR:
* `external docs`
* `security`
* `security definitions`
* `example object`
Swagger data NOT covered:
* `summary`
* `operationId`
* `tags`
Open question(s):
* should we import as attributes also `schemes`, `host`, `basePath` that are currently combined into Apidoc's *baseUrl* service property ?
Resolves #584 
Example of *api.json* obtained importing [this swagger.json file](https://github.com/fabiocognigni/apidoc/blob/584_swagger_data_attributes/swagger/src/test/resources/petstore-external-docs-example-security.json) : 
[apidoc-swagger-attribute-example.json.txt](https://github.com/mbryzek/apidoc/files/1018355/apidoc-swagger-attribute-example.json.txt)

On import, keep Swagger specific data as Apidoc attributes.

---

swagger/src/main/scala/me/apidoc/swagger/Parser.scala
swagger/src/test/resources/no-resources.json
swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala

Currently Swagger import fails (with Scala pattern matching error) if at least one of the paths' 200 response has no model type (example: string or array of string response body).
Cases like this are now ignored by ApiBuilder when looking for Resources: no errors are thrown but that resource and related paths/operations are not be imported in ApiBuilder (they cannot be imported being not objects, but at least the rest of the Swagger spec will be imported).
See the example in the issue #652 .

Handle gracefully Swagger spec with no model types in 200 response.

---

core/src/main/scala/core/builder/ServiceSpecValidator.scala
core/src/test/scala/core/ServicePathParametersSpec.scala

- Add test case for paths like /users/:id.html which we supported in past
and I think we want to continue

Use internal parser to pull out valid path parameter names

---

api/app/lib/ExampleJson.scala
api/app/lib/ServiceBuilder.scala
api/test/lib/ExampleJsonSpec.scala

* Use EnumValue 'value' instead of 'name' if available
* Use UnionType 'discriminatorValue' instead of 'type' if available
* Strip namespace from enum types
* Primitives in union without discriminator should be { `type`: { "value" : `value` } }
* Primitives in union with discriminator should use type instead of union name as discriminator

Fix various example issues with enums and primitive unions

---

api/app/lib/ExampleJson.scala
api/test/lib/ExampleJsonSpec.scala

The discriminator should only be displayed when a model or enum is viewed as the member of a union, not when it's viewed on its own.

Only include discriminator in union example, not in model or enum

---

api/app/controllers/Code.scala

- See https://github.com/apicollective/apibuilder-generator/pull/344
- Fixes:
```
Illegal header: Illegal 'user-agent' header: Invalid input ':', expected
OWS, 'EOI', tchar, product-or-comment, comment or ws (line 1, column 11):
apibuilder:0.12.87
https://app.apibuilder.io/flow/api/0.4.14/ning_1_9_client
```

Default user agent to use '-' instead of ':'

---

core/src/main/scala/core/builder/ServiceSpecValidator.scala
core/src/test/scala/core/ServiceDefaultsSpec.scala

This is dependent on https://github.com/apicollective/apibuilder-generator/pull/378 
(which introduces "receiver" - side defaulting, without which the use of optional+default will result in code generation failures) and is a dependency of 
https://github.com/apicollective/apibuilder/pull/739 (which uses the new defaulting
behavior to introduce a new first level concern to the API Builder service spec).

Relaxing validation to permit optional fields to have defaults

---

swagger/src/main/scala/me/apidoc/swagger/Parser.scala
swagger/src/main/scala/me/apidoc/swagger/Util.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Body.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Field.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Model.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Operation.scala
swagger/src/main/scala/me/apidoc/swagger/translators/Response.scala
swagger/src/test/resources/petstore-enums.json
swagger/src/test/resources/petstore-external-docs-example-security.json
swagger/src/test/scala/me/apidoc/swagger/SwaggerServiceValidatorSpec.scala
swagger/src/test/scala/me/apidoc/swagger/UtilSpec.scala

Per Swagger 2.0 docs:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#vendorExtensions
Many properties of the Swagger doc can include a free-form 'x-'-prefixed attribute.
These can be stored in the attributes for the corresponding Apibuilder model.

Carry Swagger vendor extensions through to attributes

---

DEVELOPER.md
lib/src/main/scala/UrlKey.scala

Fixes cases like https://app.apibuilder.io/flow/user/latest, where you cannot expand the operations because the class name contains a `.`, since the user model is imported from common

Don't generate . in CSS class name

---

api/app/controllers/Code.scala
api/app/controllers/Versions.scala
api/app/generated/ApicollectiveApibuilderGeneratorV0Parsers.scala
api/app/util/ApibuilderServiceImportResolver.scala
api/test/controllers/CodeSpec.scala
api/test/util/RandomPortFinder.scala
build.sbt
generated/app/ApicollectiveApibuilderGeneratorV0Client.scala
spec/apibuilder-generator.json

Adds `imported_services` (a list of `Service`) optional field to the Apibuilder code generator invocation.
introduces WireMock library needed to test the API->Generator interaction

include imported services in the Apibuilder code generator invocation

---

swagger/src/main/scala/me/apidoc/swagger/translators/Body.scala
swagger/src/test/resources/petstore-external-docs-example-security.json

Issue: when importing a body parameter with an array:
```
parameters:
- name: subscriptions
in: body
schema:
type: array
items:
$ref: '#/definitions/Subscription'
```
I was seeing this error: `java.lang.RuntimeException: Unsupported body type: class io.swagger.models.ArrayModel`.
This commit adds a test and resolves the error.

Fix bug with Swagger import that uses an array in body param

---

api/app/db/VersionsDao.scala
lib/src/test/scala/ServiceConfigurationSpec.scala

Fixes #792.
Currently migration overwrites with `org namespace` with `service namespace`.
Hence  
`org namespace=io.github.mkows` and application `playground-api`, the result is not `io.github.mkows.playground.api.v0` (as expected) but `io.github.mkows.playground.api.v0.playground.api.v0`.
This PR introduces `1 + N` db calls (up from `1`) to fetch organization namespace -- this is to not modify `Version` model (an alternative would be to have a dedicated `Version + org namespace` model).
h3. Initial description (archive)
Unit test demonstrates the issue.
Proposal of the fix -- not tested at all yet -- just code draft.
```
records.foreach { version =>
val orgKey = version.organization.key
val applicationKey = version.application.key
val versionName = version.version
val versionGuid = …
```

Fix migration - corrupt org namespace

---

.github/workflows/ci.yml
core/src/test/scala/core/ServiceValidatorSpec.scala
lib/src/main/scala/Text.scala
lib/src/test/scala/TextSpec.scala

I'm modelling [https://readme.com/](https://readme.com/)'s API. Their API responses return object IDs in the `_id` field. Apibuilder currently rejects this.

Allow names that start with an underscore

---

core/src/main/scala/core/builder/ServiceSpecValidator.scala
core/src/test/scala/core/UnionTypeDiscriminatorValueSpec.scala

Resolves https://github.com/apicollective/apibuilder/issues/818
In addition, enforce a unique discriminator key per model across union type.

Enforce a unique discriminator key and value per model across union types

---

core/src/main/scala/core/builder/ServiceSpecValidator.scala
core/src/main/scala/core/builder/api_json/ServiceBuilder.scala
core/src/test/scala/core/InterfaceSpec.scala

- in code generation, distinction between union and interface is minimal if any
- enable use of the same name to define the union and interface. Code generation
can then define the interface on the union type directly and avoid humans
needing to create two names for a single concept

Enable union and interface to share names

---

core/src/main/scala/core/builder/api_json/ApiJsonServiceValidator.scala

By adding `"$schema": "https://json.schemastore.org/apibuilder.json"` to our api.json files, we get autocompletion OOTB in VSCode, and probably better support for other editors
Related to #835

Support $schema field on api.json

---

app/app/lib/ApiClientProvider.scala

Right now we are sending 2 Authorization headers if we have a session ID:
in ECS:
```
Authorization: Session A51...
authorization: Basic UGV5Un...
```
in k8s (my guess is istio rewriting the headers):
```
authorization: Session A51...,Basic UGV5Un...
```
so the auth header parsing is failing in k8s

Only send 1 auth header to api

---

core/src/main/scala/core/builder/ServiceSpecValidator.scala
core/src/test/scala/core/NestedUnionsSpec.scala
core/src/test/scala/core/UnionTypeSpec.scala

- If a union type contains other union types, verify that one of the following is true
- all the union types define NO discriminator
- all the union types define a discriminator with the same name

Validate discriminator value across nested union types

---

core/src/main/scala/core/builder/ServiceSpecValidator.scala
core/src/test/scala/core/builder/api_json/templates/ResourceMergeSpec.scala
lib/src/main/scala/Kind.scala

- code generators currently expect types to be concrete types (not interfaces)
- this PR validates that certain types must not be interfaces where not expected
- in future, can re-evaluate this constraint to see if we should be allowing
interfaces here

Fix validation around types and interfaces

---

api/app/lib/Emails.scala
api/app/processor/CheckInvariantsProcessor.scala
api/app/processor/DiffVersionProcessor.scala
api/app/processor/EmailProcessor.scala
api/test/lib/EmailsSpec.scala
api/test/util/Daos.scala

Debug email sending for different versions

---

app/test/lib/UtilSpec.scala
build.sbt
project/plugins.sbt

Upgrade dependencies
